SELECT 
    table_schema,
    table_name,
    column_name,
    ordinal_position,
    column_default,
    is_nullable,
    data_type,
    character_maximum_length,
    numeric_precision,
    numeric_scale,
    udt_name
FROM information_schema.columns
WHERE table_schema = 'public'  -- Cambia si usas otro schema
ORDER BY table_name, ordinal_position;


"table_schema"	"table_name"	"column_name"	"ordinal_position"	"column_default"	"is_nullable"	"data_type"	"character_maximum_length"	"numeric_precision"	"numeric_scale"	"udt_name"
"public"	"Business"	"id"	1		"NO"	"text"				"text"
"public"	"Business"	"slug"	2		"NO"	"text"				"text"
"public"	"Business"	"name"	3		"NO"	"text"				"text"
"public"	"Business"	"type"	4		"NO"	"USER-DEFINED"				"BusinessType"
"public"	"Business"	"plan"	5	"'FREE'::""Plan"""	"NO"	"USER-DEFINED"				"Plan"
"public"	"Business"	"whatsapp"	6		"NO"	"text"				"text"
"public"	"Business"	"city"	7		"YES"	"text"				"text"
"public"	"Business"	"settings"	8	"'{}'::jsonb"	"NO"	"jsonb"				"jsonb"
"public"	"Business"	"isActive"	9	"true"	"NO"	"boolean"				"bool"
"public"	"Business"	"createdAt"	10	"CURRENT_TIMESTAMP"	"NO"	"timestamp without time zone"				"timestamp"
"public"	"Business"	"catalogOptions"	11		"YES"	"jsonb"				"jsonb"
"public"	"Business"	"description"	12		"YES"	"text"				"text"
"public"	"Business"	"instagram"	13		"YES"	"text"				"text"
"public"	"Business"	"paymentMethods"	14		"YES"	"jsonb"				"jsonb"
"public"	"Business"	"schedule"	15		"YES"	"text"				"text"
"public"	"Business"	"store_latitude"	16		"YES"	"double precision"		53		"float8"
"public"	"Business"	"store_longitude"	17		"YES"	"double precision"		53		"float8"
"public"	"Business"	"store_address"	18		"YES"	"character varying"	200			"varchar"
"public"	"Category"	"id"	1		"NO"	"text"				"text"
"public"	"Category"	"businessId"	2		"NO"	"text"				"text"
"public"	"Category"	"name"	3		"NO"	"text"				"text"
"public"	"Category"	"description"	4		"YES"	"text"				"text"
"public"	"Category"	"createdAt"	5	"CURRENT_TIMESTAMP"	"NO"	"timestamp without time zone"				"timestamp"
"public"	"Category"	"updatedAt"	6		"NO"	"timestamp without time zone"				"timestamp"
"public"	"Conversation"	"id"	1		"NO"	"text"				"text"
"public"	"Conversation"	"businessId"	2		"NO"	"text"				"text"
"public"	"Conversation"	"customerId"	3		"NO"	"text"				"text"
"public"	"Conversation"	"channel"	4		"NO"	"USER-DEFINED"				"Channel"
"public"	"Conversation"	"status"	5	"'BOT'::""ConvStatus"""	"NO"	"USER-DEFINED"				"ConvStatus"
"public"	"Conversation"	"botActive"	6	"true"	"NO"	"boolean"				"bool"
"public"	"Conversation"	"createdAt"	7	"CURRENT_TIMESTAMP"	"NO"	"timestamp without time zone"				"timestamp"
"public"	"Conversation"	"updatedAt"	8		"NO"	"timestamp without time zone"				"timestamp"
"public"	"Customer"	"id"	1		"NO"	"text"				"text"
"public"	"Customer"	"businessId"	2		"NO"	"text"				"text"
"public"	"Customer"	"phone"	3		"YES"	"text"				"text"
"public"	"Customer"	"name"	4		"YES"	"text"				"text"
"public"	"Customer"	"address"	5		"YES"	"text"				"text"
"public"	"Customer"	"createdAt"	6	"CURRENT_TIMESTAMP"	"NO"	"timestamp without time zone"				"timestamp"
"public"	"Customer"	"updatedAt"	7		"NO"	"timestamp without time zone"				"timestamp"
"public"	"Customer"	"addressNotes"	8		"YES"	"text"				"text"
"public"	"Customer"	"email"	9		"YES"	"text"				"text"
"public"	"Customer"	"identification"	10		"YES"	"text"				"text"
"public"	"Customer"	"preferences"	11		"YES"	"jsonb"				"jsonb"
"public"	"ExchangeRate"	"id"	1		"NO"	"text"				"text"
"public"	"ExchangeRate"	"businessId"	2		"YES"	"text"				"text"
"public"	"ExchangeRate"	"usdToVes"	3		"NO"	"numeric"		65	30	"numeric"
"public"	"ExchangeRate"	"source"	4		"NO"	"text"				"text"
"public"	"ExchangeRate"	"date"	5	"CURRENT_TIMESTAMP"	"NO"	"timestamp without time zone"				"timestamp"
"public"	"Message"	"id"	1		"NO"	"text"				"text"
"public"	"Message"	"conversationId"	2		"NO"	"text"				"text"
"public"	"Message"	"role"	3		"NO"	"USER-DEFINED"				"MsgRole"
"public"	"Message"	"content"	4		"NO"	"text"				"text"
"public"	"Message"	"mediaUrl"	5		"YES"	"text"				"text"
"public"	"Message"	"waId"	6		"YES"	"text"				"text"
"public"	"Message"	"createdAt"	7	"CURRENT_TIMESTAMP"	"NO"	"timestamp without time zone"				"timestamp"
"public"	"Order"	"id"	1		"NO"	"text"				"text"
"public"	"Order"	"orderNumber"	2	"nextval('""Order_orderNumber_seq""'::regclass)"	"NO"	"integer"		32	0	"int4"
"public"	"Order"	"businessId"	3		"NO"	"text"				"text"
"public"	"Order"	"customerId"	4		"NO"	"text"				"text"
"public"	"Order"	"status"	5	"'PENDING'::""OrderStatus"""	"NO"	"USER-DEFINED"				"OrderStatus"
"public"	"Order"	"source"	6	"'WEB'::""OrderSource"""	"NO"	"USER-DEFINED"				"OrderSource"
"public"	"Order"	"totalCents"	7		"NO"	"integer"		32	0	"int4"
"public"	"Order"	"exchangeRate"	8		"YES"	"numeric"		65	30	"numeric"
"public"	"Order"	"paymentMethod"	9		"NO"	"USER-DEFINED"				"PaymentMethod"
"public"	"Order"	"deliveryAddress"	10		"YES"	"text"				"text"
"public"	"Order"	"notes"	11		"YES"	"text"				"text"
"public"	"Order"	"createdAt"	12	"CURRENT_TIMESTAMP"	"NO"	"timestamp without time zone"				"timestamp"
"public"	"Order"	"updatedAt"	13		"NO"	"timestamp without time zone"				"timestamp"
"public"	"Order"	"shipping_zone_slug"	14		"YES"	"character varying"	50			"varchar"
"public"	"Order"	"shipping_cost_cents"	15		"YES"	"integer"		32	0	"int4"
"public"	"Order"	"shipping_method_code"	16		"YES"	"character varying"	20			"varchar"
"public"	"Order"	"delivery_lat"	17		"YES"	"double precision"		53		"float8"
"public"	"Order"	"delivery_lng"	18		"YES"	"double precision"		53		"float8"
"public"	"OrderItem"	"id"	1		"NO"	"text"				"text"
"public"	"OrderItem"	"orderId"	2		"NO"	"text"				"text"
"public"	"OrderItem"	"productId"	3		"NO"	"text"				"text"
"public"	"OrderItem"	"quantity"	4		"NO"	"integer"		32	0	"int4"
"public"	"OrderItem"	"unitPriceCents"	5		"NO"	"integer"		32	0	"int4"
"public"	"OrderItem"	"variantSelected"	6		"YES"	"jsonb"				"jsonb"
"public"	"Payment"	"id"	1		"NO"	"text"				"text"
"public"	"Payment"	"orderId"	2		"NO"	"text"				"text"
"public"	"Payment"	"businessId"	3		"NO"	"text"				"text"
"public"	"Payment"	"method"	4		"NO"	"USER-DEFINED"				"PaymentMethod"
"public"	"Payment"	"amountCents"	5		"NO"	"integer"		32	0	"int4"
"public"	"Payment"	"currency"	6		"NO"	"text"				"text"
"public"	"Payment"	"reference"	7		"YES"	"text"				"text"
"public"	"Payment"	"proofImageUrl"	8		"YES"	"text"				"text"
"public"	"Payment"	"status"	9	"'PENDING'::""PaymentStatus"""	"NO"	"USER-DEFINED"				"PaymentStatus"
"public"	"Payment"	"verifiedAt"	10		"YES"	"timestamp without time zone"				"timestamp"
"public"	"Payment"	"verifiedBy"	11		"YES"	"text"				"text"
"public"	"Payment"	"createdAt"	12	"CURRENT_TIMESTAMP"	"NO"	"timestamp without time zone"				"timestamp"
"public"	"Payment"	"notes"	13		"YES"	"text"				"text"
"public"	"PaymentConfig"	"id"	1		"NO"	"text"				"text"
"public"	"PaymentConfig"	"businessId"	2		"NO"	"text"				"text"
"public"	"PaymentConfig"	"method"	3		"NO"	"USER-DEFINED"				"PaymentMethod"
"public"	"PaymentConfig"	"details"	4	"'{}'::jsonb"	"NO"	"jsonb"				"jsonb"
"public"	"PaymentConfig"	"isActive"	5	"true"	"NO"	"boolean"				"bool"
"public"	"PaymentConfig"	"createdAt"	6	"CURRENT_TIMESTAMP"	"NO"	"timestamp without time zone"				"timestamp"
"public"	"PaymentConfig"	"updatedAt"	7		"NO"	"timestamp without time zone"				"timestamp"
"public"	"Product"	"id"	1		"NO"	"text"				"text"
"public"	"Product"	"businessId"	2		"NO"	"text"				"text"
"public"	"Product"	"categoryId"	3		"YES"	"text"				"text"
"public"	"Product"	"name"	4		"NO"	"text"				"text"
"public"	"Product"	"description"	5		"YES"	"text"				"text"
"public"	"Product"	"priceUsdCents"	6		"NO"	"integer"		32	0	"int4"
"public"	"Product"	"stock"	7	"0"	"NO"	"integer"		32	0	"int4"
"public"	"Product"	"images"	8		"YES"	"ARRAY"				"_text"
"public"	"Product"	"variants"	9	"'[]'::jsonb"	"NO"	"jsonb"				"jsonb"
"public"	"Product"	"attributes"	10	"'{}'::jsonb"	"NO"	"jsonb"				"jsonb"
"public"	"Product"	"isPublished"	11	"true"	"NO"	"boolean"				"bool"
"public"	"Product"	"deletedAt"	12		"YES"	"timestamp without time zone"				"timestamp"
"public"	"Product"	"createdAt"	13	"CURRENT_TIMESTAMP"	"NO"	"timestamp without time zone"				"timestamp"
"public"	"Product"	"updatedAt"	14		"NO"	"timestamp without time zone"				"timestamp"
"public"	"Session"	"id"	1		"NO"	"text"				"text"
"public"	"Session"	"userId"	2		"NO"	"text"				"text"
"public"	"Session"	"token"	3		"NO"	"text"				"text"
"public"	"Session"	"userAgent"	4		"YES"	"text"				"text"
"public"	"Session"	"expiresAt"	5		"NO"	"timestamp without time zone"				"timestamp"
"public"	"Session"	"revokedAt"	6		"YES"	"timestamp without time zone"				"timestamp"
"public"	"Session"	"createdAt"	7	"CURRENT_TIMESTAMP"	"NO"	"timestamp without time zone"				"timestamp"
"public"	"User"	"id"	1		"NO"	"text"				"text"
"public"	"User"	"businessId"	2		"NO"	"text"				"text"
"public"	"User"	"email"	3		"NO"	"text"				"text"
"public"	"User"	"passwordHash"	4		"NO"	"text"				"text"
"public"	"User"	"name"	5		"NO"	"text"				"text"
"public"	"User"	"role"	6	"'AGENT'::""Role"""	"NO"	"USER-DEFINED"				"Role"
"public"	"User"	"isVerified"	7	"false"	"NO"	"boolean"				"bool"
"public"	"User"	"createdAt"	8	"CURRENT_TIMESTAMP"	"NO"	"timestamp without time zone"				"timestamp"
"public"	"_prisma_migrations"	"id"	1		"NO"	"character varying"	36			"varchar"
"public"	"_prisma_migrations"	"checksum"	2		"NO"	"character varying"	64			"varchar"
"public"	"_prisma_migrations"	"finished_at"	3		"YES"	"timestamp with time zone"				"timestamptz"
"public"	"_prisma_migrations"	"migration_name"	4		"NO"	"character varying"	255			"varchar"
"public"	"_prisma_migrations"	"logs"	5		"YES"	"text"				"text"
"public"	"_prisma_migrations"	"rolled_back_at"	6		"YES"	"timestamp with time zone"				"timestamptz"
"public"	"_prisma_migrations"	"started_at"	7	"now()"	"NO"	"timestamp with time zone"				"timestamptz"
"public"	"_prisma_migrations"	"applied_steps_count"	8	"0"	"NO"	"integer"		32	0	"int4"
"public"	"bancos"	"id"	1	"nextval('bancos_id_seq'::regclass)"	"NO"	"integer"		32	0	"int4"
"public"	"bancos"	"codigo_ibp"	2		"NO"	"character varying"	4			"varchar"
"public"	"bancos"	"nombre"	3		"NO"	"character varying"	100			"varchar"
"public"	"bancos"	"nombre_corto"	4		"YES"	"character varying"	50			"varchar"
"public"	"bancos"	"activo"	5	"true"	"YES"	"boolean"				"bool"
"public"	"bancos"	"orden"	6	"0"	"YES"	"integer"		32	0	"int4"
"public"	"bancos"	"created_at"	7	"CURRENT_TIMESTAMP"	"YES"	"timestamp without time zone"				"timestamp"
"public"	"bancos"	"updated_at"	8	"CURRENT_TIMESTAMP"	"YES"	"timestamp without time zone"				"timestamp"
"public"	"estados"	"id"	1	"nextval('estados_id_seq'::regclass)"	"NO"	"integer"		32	0	"int4"
"public"	"estados"	"codigo"	2		"NO"	"character varying"	2			"varchar"
"public"	"estados"	"nombre_estado"	3		"NO"	"character varying"	100			"varchar"
"public"	"estados"	"created_at"	4	"CURRENT_TIMESTAMP"	"YES"	"timestamp without time zone"				"timestamp"
"public"	"geo_internacional"	"id"	1	"nextval('geo_internacional_id_seq'::regclass)"	"NO"	"integer"		32	0	"int4"
"public"	"geo_internacional"	"cod_estado"	2		"NO"	"character varying"	2			"varchar"
"public"	"geo_internacional"	"estado_nombre"	3		"NO"	"character varying"	100			"varchar"
"public"	"geo_internacional"	"id_municipio_edo"	4		"NO"	"character varying"	4			"varchar"
"public"	"geo_internacional"	"cod_municipio"	5		"NO"	"character varying"	2			"varchar"
"public"	"geo_internacional"	"municipio_nombre"	6		"NO"	"character varying"	100			"varchar"
"public"	"geo_internacional"	"cod_parroquia"	7		"NO"	"character varying"	2			"varchar"
"public"	"geo_internacional"	"parroquia_nombre"	8		"NO"	"character varying"	100			"varchar"
"public"	"geo_internacional"	"id_pq_mun_edo"	9		"NO"	"character varying"	6			"varchar"
"public"	"geo_internacional"	"created_at"	10	"CURRENT_TIMESTAMP"	"YES"	"timestamp without time zone"				"timestamp"
"public"	"metodos_pago"	"id"	1	"nextval('metodos_pago_id_seq'::regclass)"	"NO"	"integer"		32	0	"int4"
"public"	"metodos_pago"	"codigo"	2		"NO"	"character varying"	20			"varchar"
"public"	"metodos_pago"	"nombre"	3		"NO"	"character varying"	50			"varchar"
"public"	"metodos_pago"	"icono"	4		"YES"	"character varying"	10			"varchar"
"public"	"metodos_pago"	"descripcion"	5		"YES"	"text"				"text"
"public"	"metodos_pago"	"requiere_cuenta"	6	"true"	"YES"	"boolean"				"bool"
"public"	"metodos_pago"	"requiere_comprobante"	7	"true"	"YES"	"boolean"				"bool"
"public"	"metodos_pago"	"orden"	8	"0"	"YES"	"integer"		32	0	"int4"
"public"	"metodos_pago"	"activo"	9	"true"	"YES"	"boolean"				"bool"
"public"	"metodos_pago"	"created_at"	10	"CURRENT_TIMESTAMP"	"YES"	"timestamp without time zone"				"timestamp"
"public"	"metodos_pago"	"updated_at"	11	"CURRENT_TIMESTAMP"	"YES"	"timestamp without time zone"				"timestamp"
"public"	"municipios"	"id"	1	"nextval('municipios_id_seq'::regclass)"	"NO"	"integer"		32	0	"int4"
"public"	"municipios"	"estado_id"	2		"NO"	"integer"		32	0	"int4"
"public"	"municipios"	"nombre_municipio"	3		"NO"	"character varying"	100			"varchar"
"public"	"municipios"	"codigo"	4		"NO"	"character varying"	4			"varchar"
"public"	"municipios"	"created_at"	5	"CURRENT_TIMESTAMP"	"YES"	"timestamp without time zone"				"timestamp"
"public"	"paises"	"id"	1	"gen_random_uuid()"	"NO"	"uuid"				"uuid"
"public"	"paises"	"nombre"	2		"NO"	"character varying"	100			"varchar"
"public"	"paises"	"iso3"	3		"NO"	"character varying"	3			"varchar"
"public"	"paises"	"iso_code"	4		"NO"	"character varying"	3			"varchar"
"public"	"paises"	"iso2"	5		"YES"	"character varying"	2			"varchar"
"public"	"paises"	"phone_code"	6		"YES"	"character varying"	10			"varchar"
"public"	"paises"	"created_at"	7	"CURRENT_TIMESTAMP"	"YES"	"timestamp with time zone"				"timestamptz"
"public"	"paises"	"updated_at"	8	"CURRENT_TIMESTAMP"	"YES"	"timestamp with time zone"				"timestamptz"
"public"	"parroquias"	"id"	1	"nextval('parroquias_id_seq'::regclass)"	"NO"	"integer"		32	0	"int4"
"public"	"parroquias"	"municipio_id"	2		"NO"	"integer"		32	0	"int4"
"public"	"parroquias"	"nombre_parroquia"	3		"NO"	"character varying"	100			"varchar"
"public"	"parroquias"	"codigo"	4		"NO"	"character varying"	6			"varchar"
"public"	"parroquias"	"created_at"	5	"CURRENT_TIMESTAMP"	"YES"	"timestamp without time zone"				"timestamp"
"public"	"regimenes_islr"	"id"	1	"nextval('regimenes_islr_id_seq'::regclass)"	"NO"	"integer"		32	0	"int4"
"public"	"regimenes_islr"	"codigo"	2		"NO"	"character varying"	20			"varchar"
"public"	"regimenes_islr"	"nombre"	3		"NO"	"character varying"	50			"varchar"
"public"	"regimenes_islr"	"descripcion"	4		"YES"	"text"				"text"
"public"	"regimenes_islr"	"porcentaje_base"	5		"YES"	"numeric"		5	2	"numeric"
"public"	"regimenes_islr"	"requiere_declaracion"	6	"true"	"YES"	"boolean"				"bool"
"public"	"regimenes_islr"	"activo"	7	"true"	"YES"	"boolean"				"bool"
"public"	"regimenes_islr"	"orden"	8	"0"	"YES"	"integer"		32	0	"int4"
"public"	"regimenes_islr"	"created_at"	9	"CURRENT_TIMESTAMP"	"YES"	"timestamp without time zone"				"timestamp"
"public"	"shipping_methods"	"id"	1	"nextval('shipping_methods_id_seq'::regclass)"	"NO"	"integer"		32	0	"int4"
"public"	"shipping_methods"	"code"	2		"NO"	"character varying"	20			"varchar"
"public"	"shipping_methods"	"name"	3		"NO"	"character varying"	50			"varchar"
"public"	"shipping_methods"	"icon"	4		"YES"	"character varying"	10			"varchar"
"public"	"shipping_methods"	"description"	5		"YES"	"text"				"text"
"public"	"shipping_methods"	"isActive"	6	"true"	"YES"	"boolean"				"bool"
"public"	"shipping_methods"	"createdAt"	7	"CURRENT_TIMESTAMP"	"YES"	"timestamp without time zone"				"timestamp"
"public"	"shipping_rates"	"id"	1	"nextval('shipping_rates_id_seq'::regclass)"	"NO"	"integer"		32	0	"int4"
"public"	"shipping_rates"	"zoneId"	2		"NO"	"integer"		32	0	"int4"
"public"	"shipping_rates"	"methodId"	3		"NO"	"integer"		32	0	"int4"
"public"	"shipping_rates"	"costType"	4	"'fixed'::character varying"	"NO"	"character varying"	10			"varchar"
"public"	"shipping_rates"	"costValue"	5		"NO"	"numeric"		10	2	"numeric"
"public"	"shipping_rates"	"minOrderAmount"	6	"0"	"YES"	"numeric"		10	2	"numeric"
"public"	"shipping_rates"	"isFree"	7	"false"	"YES"	"boolean"				"bool"
"public"	"shipping_rates"	"isActive"	8	"true"	"YES"	"boolean"				"bool"
"public"	"shipping_rates"	"createdAt"	9	"CURRENT_TIMESTAMP"	"YES"	"timestamp without time zone"				"timestamp"
"public"	"shipping_zones"	"id"	1	"nextval('shipping_zones_id_seq'::regclass)"	"NO"	"integer"		32	0	"int4"
"public"	"shipping_zones"	"businessId"	2		"NO"	"text"				"text"
"public"	"shipping_zones"	"name"	3		"NO"	"character varying"	100			"varchar"
"public"	"shipping_zones"	"slug"	4		"NO"	"character varying"	50			"varchar"
"public"	"shipping_zones"	"description"	5		"YES"	"text"				"text"
"public"	"shipping_zones"	"deliveryTime"	6		"YES"	"character varying"	50			"varchar"
"public"	"shipping_zones"	"isActive"	7	"true"	"YES"	"boolean"				"bool"
"public"	"shipping_zones"	"createdAt"	8	"CURRENT_TIMESTAMP"	"YES"	"timestamp without time zone"				"timestamp"
"public"	"tipos_documento"	"id"	1	"nextval('tipos_documento_id_seq'::regclass)"	"NO"	"integer"		32	0	"int4"
"public"	"tipos_documento"	"codigo"	2		"NO"	"character varying"	4			"varchar"
"public"	"tipos_documento"	"nombre"	3		"NO"	"character varying"	50			"varchar"
"public"	"tipos_documento"	"mascara"	4		"YES"	"character varying"	20			"varchar"
"public"	"tipos_documento"	"longitud_min"	5	"7"	"YES"	"integer"		32	0	"int4"
"public"	"tipos_documento"	"longitud_max"	6	"12"	"YES"	"integer"		32	0	"int4"
"public"	"tipos_documento"	"requiere_digito_verificador"	7	"false"	"YES"	"boolean"				"bool"
"public"	"tipos_documento"	"activo"	8	"true"	"YES"	"boolean"				"bool"
"public"	"tipos_documento"	"orden"	9	"0"	"YES"	"integer"		32	0	"int4"
"public"	"tipos_documento"	"created_at"	10	"CURRENT_TIMESTAMP"	"YES"	"timestamp without time zone"				"timestamp"
"public"	"tipos_negocio"	"id"	1	"nextval('tipos_negocio_id_seq'::regclass)"	"NO"	"integer"		32	0	"int4"
"public"	"tipos_negocio"	"codigo"	2		"NO"	"character varying"	20			"varchar"
"public"	"tipos_negocio"	"nombre"	3		"NO"	"character varying"	50			"varchar"
"public"	"tipos_negocio"	"icono"	4		"YES"	"character varying"	10			"varchar"
"public"	"tipos_negocio"	"descripcion"	5		"YES"	"text"				"text"
"public"	"tipos_negocio"	"campos_especiales"	6		"YES"	"jsonb"				"jsonb"
"public"	"tipos_negocio"	"activo"	7	"true"	"YES"	"boolean"				"bool"
"public"	"tipos_negocio"	"orden"	8	"0"	"YES"	"integer"		32	0	"int4"
"public"	"tipos_negocio"	"created_at"	9	"CURRENT_TIMESTAMP"	"YES"	"timestamp without time zone"				"timestamp"
"public"	"tipos_negocio"	"updated_at"	10	"CURRENT_TIMESTAMP"	"YES"	"timestamp without time zone"				"timestamp"
"public"	"tipos_persona"	"id"	1	"nextval('tipos_persona_id_seq'::regclass)"	"NO"	"integer"		32	0	"int4"
"public"	"tipos_persona"	"codigo"	2		"NO"	"character varying"	10			"varchar"
"public"	"tipos_persona"	"nombre"	3		"NO"	"character varying"	50			"varchar"
"public"	"tipos_persona"	"descripcion"	4		"YES"	"text"				"text"
"public"	"tipos_persona"	"requiere_razon_social"	5	"false"	"YES"	"boolean"				"bool"
"public"	"tipos_persona"	"requiere_nombre_completo"	6	"true"	"YES"	"boolean"				"bool"
"public"	"tipos_persona"	"campos_adicionales"	7		"YES"	"jsonb"				"jsonb"
"public"	"tipos_persona"	"activo"	8	"true"	"YES"	"boolean"				"bool"
"public"	"tipos_persona"	"orden"	9	"0"	"YES"	"integer"		32	0	"int4"
"public"	"tipos_persona"	"created_at"	10	"CURRENT_TIMESTAMP"	"YES"	"timestamp without time zone"				"timestamp"
"public"	"zonas_entrega"	"id"	1	"nextval('zonas_entrega_id_seq'::regclass)"	"NO"	"integer"		32	0	"int4"
"public"	"zonas_entrega"	"estado_codigo"	2		"NO"	"character varying"	2			"varchar"
"public"	"zonas_entrega"	"estado_nombre"	3		"NO"	"character varying"	100			"varchar"
"public"	"zonas_entrega"	"zona_codigo"	4		"NO"	"character varying"	4			"varchar"
"public"	"zonas_entrega"	"zona_nombre"	5		"NO"	"character varying"	150			"varchar"
"public"	"zonas_entrega"	"activo"	6	"true"	"YES"	"boolean"				"bool"
"public"	"zonas_entrega"	"created_at"	7	"CURRENT_TIMESTAMP"	"YES"	"timestamp without time zone"				"timestamp"
"public"	"zonas_entrega"	"updated_at"	8	"CURRENT_TIMESTAMP"	"YES"	"timestamp without time zone"				"timestamp"


SELECT 
    tc.table_name,
    kcu.column_name,
    ccu.table_name AS foreign_table,
    ccu.column_name AS foreign_column,
    rc.update_rule,
    rc.delete_rule
FROM information_schema.table_constraints tc
JOIN information_schema.key_column_usage kcu 
    ON tc.constraint_name = kcu.constraint_name
JOIN information_schema.constraint_column_usage ccu 
    ON ccu.constraint_name = tc.constraint_name
JOIN information_schema.referential_constraints rc 
    ON rc.constraint_name = tc.constraint_name
WHERE tc.constraint_type = 'FOREIGN KEY'
  AND tc.table_schema = 'public'
ORDER BY tc.table_name;


"table_name"	"column_name"	"foreign_table"	"foreign_column"	"update_rule"	"delete_rule"
"Category"	"businessId"	"Business"	"id"	"CASCADE"	"RESTRICT"
"Conversation"	"customerId"	"Customer"	"id"	"CASCADE"	"RESTRICT"
"Conversation"	"businessId"	"Business"	"id"	"CASCADE"	"RESTRICT"
"Customer"	"businessId"	"Business"	"id"	"CASCADE"	"RESTRICT"
"ExchangeRate"	"businessId"	"Business"	"id"	"CASCADE"	"SET NULL"
"Message"	"conversationId"	"Conversation"	"id"	"CASCADE"	"RESTRICT"
"Order"	"businessId"	"Business"	"id"	"CASCADE"	"RESTRICT"
"Order"	"customerId"	"Customer"	"id"	"CASCADE"	"RESTRICT"
"OrderItem"	"orderId"	"Order"	"id"	"CASCADE"	"RESTRICT"
"OrderItem"	"productId"	"Product"	"id"	"CASCADE"	"RESTRICT"
"Payment"	"orderId"	"Order"	"id"	"CASCADE"	"RESTRICT"
"Payment"	"businessId"	"Business"	"id"	"CASCADE"	"RESTRICT"
"PaymentConfig"	"businessId"	"Business"	"id"	"CASCADE"	"RESTRICT"
"Product"	"categoryId"	"Category"	"id"	"CASCADE"	"SET NULL"
"Product"	"businessId"	"Business"	"id"	"CASCADE"	"RESTRICT"
"Session"	"userId"	"User"	"id"	"CASCADE"	"RESTRICT"
"User"	"businessId"	"Business"	"id"	"CASCADE"	"RESTRICT"
"municipios"	"estado_id"	"estados"	"id"	"NO ACTION"	"CASCADE"
"parroquias"	"municipio_id"	"municipios"	"id"	"NO ACTION"	"CASCADE"
"shipping_rates"	"zoneId"	"shipping_zones"	"id"	"NO ACTION"	"CASCADE"
"shipping_rates"	"methodId"	"shipping_methods"	"id"	"NO ACTION"	"CASCADE"
"shipping_zones"	"businessId"	"Business"	"id"	"NO ACTION"	"CASCADE"


SELECT 
    tc.table_name,
    kcu.column_name,
    tc.constraint_name,
    tc.constraint_type
FROM information_schema.table_constraints tc
JOIN information_schema.key_column_usage kcu 
    ON tc.constraint_name = kcu.constraint_name
WHERE tc.table_schema = 'public'
  AND tc.constraint_type IN ('PRIMARY KEY', 'UNIQUE')
ORDER BY tc.table_name, kcu.ordinal_position;


"table_name"	"column_name"	"constraint_name"	"constraint_type"
"Business"	"id"	"Business_pkey"	"PRIMARY KEY"
"Category"	"id"	"Category_pkey"	"PRIMARY KEY"
"Conversation"	"id"	"Conversation_pkey"	"PRIMARY KEY"
"Customer"	"id"	"Customer_pkey"	"PRIMARY KEY"
"ExchangeRate"	"id"	"ExchangeRate_pkey"	"PRIMARY KEY"
"Message"	"id"	"Message_pkey"	"PRIMARY KEY"
"Order"	"id"	"Order_pkey"	"PRIMARY KEY"
"OrderItem"	"id"	"OrderItem_pkey"	"PRIMARY KEY"
"Payment"	"id"	"Payment_pkey"	"PRIMARY KEY"
"PaymentConfig"	"id"	"PaymentConfig_pkey"	"PRIMARY KEY"
"Product"	"id"	"Product_pkey"	"PRIMARY KEY"
"Session"	"id"	"Session_pkey"	"PRIMARY KEY"
"User"	"id"	"User_pkey"	"PRIMARY KEY"
"_prisma_migrations"	"id"	"_prisma_migrations_pkey"	"PRIMARY KEY"
"bancos"	"id"	"bancos_pkey"	"PRIMARY KEY"
"bancos"	"codigo_ibp"	"bancos_codigo_ibp_key"	"UNIQUE"
"estados"	"id"	"estados_pkey"	"PRIMARY KEY"
"estados"	"codigo"	"estados_codigo_key"	"UNIQUE"
"geo_internacional"	"id"	"geo_internacional_pkey"	"PRIMARY KEY"
"geo_internacional"	"id_pq_mun_edo"	"geo_internacional_id_pq_mun_edo_key"	"UNIQUE"
"metodos_pago"	"id"	"metodos_pago_pkey"	"PRIMARY KEY"
"metodos_pago"	"codigo"	"metodos_pago_codigo_key"	"UNIQUE"
"municipios"	"id"	"municipios_pkey"	"PRIMARY KEY"
"municipios"	"codigo"	"municipios_codigo_key"	"UNIQUE"
"paises"	"id"	"paises_pkey"	"PRIMARY KEY"
"paises"	"iso_code"	"paises_iso_code_key"	"UNIQUE"
"paises"	"iso3"	"paises_iso3_key"	"UNIQUE"
"paises"	"nombre"	"paises_nombre_key"	"UNIQUE"
"parroquias"	"id"	"parroquias_pkey"	"PRIMARY KEY"
"parroquias"	"codigo"	"parroquias_codigo_key"	"UNIQUE"
"regimenes_islr"	"codigo"	"regimenes_islr_codigo_key"	"UNIQUE"
"regimenes_islr"	"id"	"regimenes_islr_pkey"	"PRIMARY KEY"
"shipping_methods"	"id"	"shipping_methods_pkey"	"PRIMARY KEY"
"shipping_methods"	"code"	"shipping_methods_code_key"	"UNIQUE"
"shipping_rates"	"id"	"shipping_rates_pkey"	"PRIMARY KEY"
"shipping_rates"	"zoneId"	"shipping_rates_zoneid_methodid_costtype_costvalue_key"	"UNIQUE"
"shipping_rates"	"methodId"	"shipping_rates_zoneid_methodid_costtype_costvalue_key"	"UNIQUE"
"shipping_rates"	"costType"	"shipping_rates_zoneid_methodid_costtype_costvalue_key"	"UNIQUE"
"shipping_rates"	"costValue"	"shipping_rates_zoneid_methodid_costtype_costvalue_key"	"UNIQUE"
"shipping_zones"	"businessId"	"shipping_zones_businessid_slug_key"	"UNIQUE"
"shipping_zones"	"id"	"shipping_zones_pkey"	"PRIMARY KEY"
"shipping_zones"	"slug"	"shipping_zones_businessid_slug_key"	"UNIQUE"
"tipos_documento"	"codigo"	"tipos_documento_codigo_key"	"UNIQUE"
"tipos_documento"	"id"	"tipos_documento_pkey"	"PRIMARY KEY"
"tipos_negocio"	"id"	"tipos_negocio_pkey"	"PRIMARY KEY"
"tipos_negocio"	"codigo"	"tipos_negocio_codigo_key"	"UNIQUE"
"tipos_persona"	"id"	"tipos_persona_pkey"	"PRIMARY KEY"
"tipos_persona"	"codigo"	"tipos_persona_codigo_key"	"UNIQUE"
"zonas_entrega"	"estado_codigo"	"zonas_entrega_unique"	"UNIQUE"
"zonas_entrega"	"id"	"zonas_entrega_pkey"	"PRIMARY KEY"
"zonas_entrega"	"zona_codigo"	"zonas_entrega_unique"	"UNIQUE"
"zonas_entrega"	"zona_nombre"	"zonas_entrega_unique"	"UNIQUE"


 -- Exporta esto a CSV para comparar con schema.prisma
SELECT 
    t.table_name,
    c.column_name,
    c.data_type,
    c.is_nullable,
    c.column_default,
    CASE 
        WHEN tc.constraint_type = 'PRIMARY KEY' THEN 'PK'
        WHEN tc.constraint_type = 'FOREIGN KEY' THEN 'FK'
        WHEN tc.constraint_type = 'UNIQUE' THEN 'UQ'
        ELSE NULL 
    END AS constraint_type,
    fk_info.referenced_table,
    fk_info.referenced_column
FROM information_schema.tables t
JOIN information_schema.columns c 
    ON t.table_name = c.table_name
LEFT JOIN information_schema.key_column_usage kcu 
    ON c.table_name = kcu.table_name 
    AND c.column_name = kcu.column_name
LEFT JOIN information_schema.table_constraints tc 
    ON kcu.constraint_name = tc.constraint_name
LEFT JOIN (
    SELECT 
        kcu.table_name,
        kcu.column_name,
        ccu.table_name AS referenced_table,
        ccu.column_name AS referenced_column
    FROM information_schema.key_column_usage kcu
    JOIN information_schema.constraint_column_usage ccu 
        ON kcu.constraint_name = ccu.constraint_name
    WHERE kcu.constraint_name IN (
        SELECT constraint_name 
        FROM information_schema.table_constraints 
        WHERE constraint_type = 'FOREIGN KEY'
    )
) fk_info 
    ON c.table_name = fk_info.table_name 
    AND c.column_name = fk_info.column_name
WHERE t.table_schema = 'public'
  AND t.table_type = 'BASE TABLE'
ORDER BY t.table_name, c.ordinal_position;

"table_name"	"column_name"	"data_type"	"is_nullable"	"column_default"	"constraint_type"	"referenced_table"	"referenced_column"
"Business"	"id"	"text"	"NO"		"PK"		
"Business"	"slug"	"text"	"NO"				
"Business"	"name"	"text"	"NO"				
"Business"	"type"	"USER-DEFINED"	"NO"				
"Business"	"plan"	"USER-DEFINED"	"NO"	"'FREE'::""Plan"""			
"Business"	"whatsapp"	"text"	"NO"				
"Business"	"city"	"text"	"YES"				
"Business"	"settings"	"jsonb"	"NO"	"'{}'::jsonb"			
"Business"	"isActive"	"boolean"	"NO"	"true"			
"Business"	"createdAt"	"timestamp without time zone"	"NO"	"CURRENT_TIMESTAMP"			
"Business"	"catalogOptions"	"jsonb"	"YES"				
"Business"	"description"	"text"	"YES"				
"Business"	"instagram"	"text"	"YES"				
"Business"	"paymentMethods"	"jsonb"	"YES"				
"Business"	"schedule"	"text"	"YES"				
"Business"	"store_latitude"	"double precision"	"YES"				
"Business"	"store_longitude"	"double precision"	"YES"				
"Business"	"store_address"	"character varying"	"YES"				
"Category"	"id"	"text"	"NO"		"PK"		
"Category"	"businessId"	"text"	"NO"		"FK"	"Business"	"id"
"Category"	"name"	"text"	"NO"				
"Category"	"description"	"text"	"YES"				
"Category"	"createdAt"	"timestamp without time zone"	"NO"	"CURRENT_TIMESTAMP"			
"Category"	"updatedAt"	"timestamp without time zone"	"NO"				
"Conversation"	"id"	"text"	"NO"		"PK"		
"Conversation"	"businessId"	"text"	"NO"		"FK"	"Business"	"id"
"Conversation"	"customerId"	"text"	"NO"		"FK"	"Customer"	"id"
"Conversation"	"channel"	"USER-DEFINED"	"NO"				
"Conversation"	"status"	"USER-DEFINED"	"NO"	"'BOT'::""ConvStatus"""			
"Conversation"	"botActive"	"boolean"	"NO"	"true"			
"Conversation"	"createdAt"	"timestamp without time zone"	"NO"	"CURRENT_TIMESTAMP"			
"Conversation"	"updatedAt"	"timestamp without time zone"	"NO"				
"Customer"	"id"	"text"	"NO"		"PK"		
"Customer"	"businessId"	"text"	"NO"		"FK"	"Business"	"id"
"Customer"	"phone"	"text"	"YES"				
"Customer"	"name"	"text"	"YES"				
"Customer"	"address"	"text"	"YES"				
"Customer"	"createdAt"	"timestamp without time zone"	"NO"	"CURRENT_TIMESTAMP"			
"Customer"	"updatedAt"	"timestamp without time zone"	"NO"				
"Customer"	"addressNotes"	"text"	"YES"				
"Customer"	"email"	"text"	"YES"				
"Customer"	"identification"	"text"	"YES"				
"Customer"	"preferences"	"jsonb"	"YES"				
"ExchangeRate"	"id"	"text"	"NO"		"PK"		
"ExchangeRate"	"businessId"	"text"	"YES"		"FK"	"Business"	"id"
"ExchangeRate"	"usdToVes"	"numeric"	"NO"				
"ExchangeRate"	"source"	"text"	"NO"				
"ExchangeRate"	"date"	"timestamp without time zone"	"NO"	"CURRENT_TIMESTAMP"			
"Message"	"id"	"text"	"NO"		"PK"		
"Message"	"conversationId"	"text"	"NO"		"FK"	"Conversation"	"id"
"Message"	"role"	"USER-DEFINED"	"NO"				
"Message"	"content"	"text"	"NO"				
"Message"	"mediaUrl"	"text"	"YES"				
"Message"	"waId"	"text"	"YES"				
"Message"	"createdAt"	"timestamp without time zone"	"NO"	"CURRENT_TIMESTAMP"			
"Order"	"id"	"text"	"NO"		"PK"		
"Order"	"orderNumber"	"integer"	"NO"	"nextval('""Order_orderNumber_seq""'::regclass)"			
"Order"	"businessId"	"text"	"NO"		"FK"	"Business"	"id"
"Order"	"customerId"	"text"	"NO"		"FK"	"Customer"	"id"
"Order"	"status"	"USER-DEFINED"	"NO"	"'PENDING'::""OrderStatus"""			
"Order"	"source"	"USER-DEFINED"	"NO"	"'WEB'::""OrderSource"""			
"Order"	"totalCents"	"integer"	"NO"				
"Order"	"exchangeRate"	"numeric"	"YES"				
"Order"	"paymentMethod"	"USER-DEFINED"	"NO"				
"Order"	"deliveryAddress"	"text"	"YES"				
"Order"	"notes"	"text"	"YES"				
"Order"	"createdAt"	"timestamp without time zone"	"NO"	"CURRENT_TIMESTAMP"			
"Order"	"updatedAt"	"timestamp without time zone"	"NO"				
"Order"	"shipping_zone_slug"	"character varying"	"YES"				
"Order"	"shipping_cost_cents"	"integer"	"YES"				
"Order"	"shipping_method_code"	"character varying"	"YES"				
"Order"	"delivery_lat"	"double precision"	"YES"				
"Order"	"delivery_lng"	"double precision"	"YES"				
"OrderItem"	"id"	"text"	"NO"		"PK"		
"OrderItem"	"orderId"	"text"	"NO"		"FK"	"Order"	"id"
"OrderItem"	"productId"	"text"	"NO"		"FK"	"Product"	"id"
"OrderItem"	"quantity"	"integer"	"NO"				
"OrderItem"	"unitPriceCents"	"integer"	"NO"				
"OrderItem"	"variantSelected"	"jsonb"	"YES"				
"Payment"	"id"	"text"	"NO"		"PK"		
"Payment"	"orderId"	"text"	"NO"		"FK"	"Order"	"id"
"Payment"	"businessId"	"text"	"NO"		"FK"	"Business"	"id"
"Payment"	"method"	"USER-DEFINED"	"NO"				
"Payment"	"amountCents"	"integer"	"NO"				
"Payment"	"currency"	"text"	"NO"				
"Payment"	"reference"	"text"	"YES"				
"Payment"	"proofImageUrl"	"text"	"YES"				
"Payment"	"status"	"USER-DEFINED"	"NO"	"'PENDING'::""PaymentStatus"""			
"Payment"	"verifiedAt"	"timestamp without time zone"	"YES"				
"Payment"	"verifiedBy"	"text"	"YES"				
"Payment"	"createdAt"	"timestamp without time zone"	"NO"	"CURRENT_TIMESTAMP"			
"Payment"	"notes"	"text"	"YES"				
"PaymentConfig"	"id"	"text"	"NO"		"PK"		
"PaymentConfig"	"businessId"	"text"	"NO"		"FK"	"Business"	"id"
"PaymentConfig"	"method"	"USER-DEFINED"	"NO"				
"PaymentConfig"	"details"	"jsonb"	"NO"	"'{}'::jsonb"			
"PaymentConfig"	"isActive"	"boolean"	"NO"	"true"			
"PaymentConfig"	"createdAt"	"timestamp without time zone"	"NO"	"CURRENT_TIMESTAMP"			
"PaymentConfig"	"updatedAt"	"timestamp without time zone"	"NO"				
"Product"	"id"	"text"	"NO"		"PK"		
"Product"	"businessId"	"text"	"NO"		"FK"	"Business"	"id"
"Product"	"categoryId"	"text"	"YES"		"FK"	"Category"	"id"
"Product"	"name"	"text"	"NO"				
"Product"	"description"	"text"	"YES"				
"Product"	"priceUsdCents"	"integer"	"NO"				
"Product"	"stock"	"integer"	"NO"	"0"			
"Product"	"images"	"ARRAY"	"YES"				
"Product"	"variants"	"jsonb"	"NO"	"'[]'::jsonb"			
"Product"	"attributes"	"jsonb"	"NO"	"'{}'::jsonb"			
"Product"	"isPublished"	"boolean"	"NO"	"true"			
"Product"	"deletedAt"	"timestamp without time zone"	"YES"				
"Product"	"createdAt"	"timestamp without time zone"	"NO"	"CURRENT_TIMESTAMP"			
"Product"	"updatedAt"	"timestamp without time zone"	"NO"				
"Session"	"id"	"text"	"NO"		"PK"		
"Session"	"userId"	"text"	"NO"		"FK"	"User"	"id"
"Session"	"token"	"text"	"NO"				
"Session"	"userAgent"	"text"	"YES"				
"Session"	"expiresAt"	"timestamp without time zone"	"NO"				
"Session"	"revokedAt"	"timestamp without time zone"	"YES"				
"Session"	"createdAt"	"timestamp without time zone"	"NO"	"CURRENT_TIMESTAMP"			
"User"	"id"	"text"	"NO"		"PK"		
"User"	"businessId"	"text"	"NO"		"FK"	"Business"	"id"
"User"	"email"	"text"	"NO"				
"User"	"passwordHash"	"text"	"NO"				
"User"	"name"	"text"	"NO"				
"User"	"role"	"USER-DEFINED"	"NO"	"'AGENT'::""Role"""			
"User"	"isVerified"	"boolean"	"NO"	"false"			
"User"	"createdAt"	"timestamp without time zone"	"NO"	"CURRENT_TIMESTAMP"			
"_prisma_migrations"	"id"	"character varying"	"NO"		"PK"		
"_prisma_migrations"	"checksum"	"character varying"	"NO"				
"_prisma_migrations"	"finished_at"	"timestamp with time zone"	"YES"				
"_prisma_migrations"	"migration_name"	"character varying"	"NO"				
"_prisma_migrations"	"logs"	"text"	"YES"				
"_prisma_migrations"	"rolled_back_at"	"timestamp with time zone"	"YES"				
"_prisma_migrations"	"started_at"	"timestamp with time zone"	"NO"	"now()"			
"_prisma_migrations"	"applied_steps_count"	"integer"	"NO"	"0"			
"bancos"	"id"	"integer"	"NO"	"nextval('bancos_id_seq'::regclass)"	"PK"		
"bancos"	"codigo_ibp"	"character varying"	"NO"		"UQ"		
"bancos"	"nombre"	"character varying"	"NO"				
"bancos"	"nombre_corto"	"character varying"	"YES"				
"bancos"	"activo"	"boolean"	"YES"	"true"			
"bancos"	"orden"	"integer"	"YES"	"0"			
"bancos"	"created_at"	"timestamp without time zone"	"YES"	"CURRENT_TIMESTAMP"			
"bancos"	"updated_at"	"timestamp without time zone"	"YES"	"CURRENT_TIMESTAMP"			
"estados"	"id"	"integer"	"NO"	"nextval('estados_id_seq'::regclass)"	"PK"		
"estados"	"codigo"	"character varying"	"NO"		"UQ"		
"estados"	"nombre_estado"	"character varying"	"NO"				
"estados"	"created_at"	"timestamp without time zone"	"YES"	"CURRENT_TIMESTAMP"			
"geo_internacional"	"id"	"integer"	"NO"	"nextval('geo_internacional_id_seq'::regclass)"	"PK"		
"geo_internacional"	"cod_estado"	"character varying"	"NO"				
"geo_internacional"	"estado_nombre"	"character varying"	"NO"				
"geo_internacional"	"id_municipio_edo"	"character varying"	"NO"				
"geo_internacional"	"cod_municipio"	"character varying"	"NO"				
"geo_internacional"	"municipio_nombre"	"character varying"	"NO"				
"geo_internacional"	"cod_parroquia"	"character varying"	"NO"				
"geo_internacional"	"parroquia_nombre"	"character varying"	"NO"				
"geo_internacional"	"id_pq_mun_edo"	"character varying"	"NO"		"UQ"		
"geo_internacional"	"created_at"	"timestamp without time zone"	"YES"	"CURRENT_TIMESTAMP"			
"metodos_pago"	"id"	"integer"	"NO"	"nextval('metodos_pago_id_seq'::regclass)"	"PK"		
"metodos_pago"	"codigo"	"character varying"	"NO"		"UQ"		
"metodos_pago"	"nombre"	"character varying"	"NO"				
"metodos_pago"	"icono"	"character varying"	"YES"				
"metodos_pago"	"descripcion"	"text"	"YES"				
"metodos_pago"	"requiere_cuenta"	"boolean"	"YES"	"true"			
"metodos_pago"	"requiere_comprobante"	"boolean"	"YES"	"true"			
"metodos_pago"	"orden"	"integer"	"YES"	"0"			
"metodos_pago"	"activo"	"boolean"	"YES"	"true"			
"metodos_pago"	"created_at"	"timestamp without time zone"	"YES"	"CURRENT_TIMESTAMP"			
"metodos_pago"	"updated_at"	"timestamp without time zone"	"YES"	"CURRENT_TIMESTAMP"			
"municipios"	"id"	"integer"	"NO"	"nextval('municipios_id_seq'::regclass)"	"PK"		
"municipios"	"estado_id"	"integer"	"NO"		"FK"	"estados"	"id"
"municipios"	"nombre_municipio"	"character varying"	"NO"				
"municipios"	"codigo"	"character varying"	"NO"		"UQ"		
"municipios"	"created_at"	"timestamp without time zone"	"YES"	"CURRENT_TIMESTAMP"			
"paises"	"id"	"uuid"	"NO"	"gen_random_uuid()"	"PK"		
"paises"	"nombre"	"character varying"	"NO"		"UQ"		
"paises"	"iso3"	"character varying"	"NO"		"UQ"		
"paises"	"iso_code"	"character varying"	"NO"		"UQ"		
"paises"	"iso2"	"character varying"	"YES"				
"paises"	"phone_code"	"character varying"	"YES"				
"paises"	"created_at"	"timestamp with time zone"	"YES"	"CURRENT_TIMESTAMP"			
"paises"	"updated_at"	"timestamp with time zone"	"YES"	"CURRENT_TIMESTAMP"			
"parroquias"	"id"	"integer"	"NO"	"nextval('parroquias_id_seq'::regclass)"	"PK"		
"parroquias"	"municipio_id"	"integer"	"NO"		"FK"	"municipios"	"id"
"parroquias"	"nombre_parroquia"	"character varying"	"NO"				
"parroquias"	"codigo"	"character varying"	"NO"		"UQ"		
"parroquias"	"created_at"	"timestamp without time zone"	"YES"	"CURRENT_TIMESTAMP"			
"regimenes_islr"	"id"	"integer"	"NO"	"nextval('regimenes_islr_id_seq'::regclass)"	"PK"		
"regimenes_islr"	"codigo"	"character varying"	"NO"		"UQ"		
"regimenes_islr"	"nombre"	"character varying"	"NO"				
"regimenes_islr"	"descripcion"	"text"	"YES"				
"regimenes_islr"	"porcentaje_base"	"numeric"	"YES"				
"regimenes_islr"	"requiere_declaracion"	"boolean"	"YES"	"true"			
"regimenes_islr"	"activo"	"boolean"	"YES"	"true"			
"regimenes_islr"	"orden"	"integer"	"YES"	"0"			
"regimenes_islr"	"created_at"	"timestamp without time zone"	"YES"	"CURRENT_TIMESTAMP"			
"shipping_methods"	"id"	"integer"	"NO"	"nextval('shipping_methods_id_seq'::regclass)"	"PK"		
"shipping_methods"	"code"	"character varying"	"NO"		"UQ"		
"shipping_methods"	"name"	"character varying"	"NO"				
"shipping_methods"	"icon"	"character varying"	"YES"				
"shipping_methods"	"description"	"text"	"YES"				
"shipping_methods"	"isActive"	"boolean"	"YES"	"true"			
"shipping_methods"	"createdAt"	"timestamp without time zone"	"YES"	"CURRENT_TIMESTAMP"			
"shipping_rates"	"id"	"integer"	"NO"	"nextval('shipping_rates_id_seq'::regclass)"	"PK"		
"shipping_rates"	"zoneId"	"integer"	"NO"		"UQ"	"shipping_zones"	"id"
"shipping_rates"	"zoneId"	"integer"	"NO"		"FK"	"shipping_zones"	"id"
"shipping_rates"	"methodId"	"integer"	"NO"		"FK"	"shipping_methods"	"id"
"shipping_rates"	"methodId"	"integer"	"NO"		"UQ"	"shipping_methods"	"id"
"shipping_rates"	"costType"	"character varying"	"NO"	"'fixed'::character varying"	"UQ"		
"shipping_rates"	"costValue"	"numeric"	"NO"		"UQ"		
"shipping_rates"	"minOrderAmount"	"numeric"	"YES"	"0"			
"shipping_rates"	"isFree"	"boolean"	"YES"	"false"			
"shipping_rates"	"isActive"	"boolean"	"YES"	"true"			
"shipping_rates"	"createdAt"	"timestamp without time zone"	"YES"	"CURRENT_TIMESTAMP"			
"shipping_zones"	"id"	"integer"	"NO"	"nextval('shipping_zones_id_seq'::regclass)"	"PK"		
"shipping_zones"	"businessId"	"text"	"NO"		"UQ"	"Business"	"id"
"shipping_zones"	"businessId"	"text"	"NO"		"FK"	"Business"	"id"
"shipping_zones"	"name"	"character varying"	"NO"				
"shipping_zones"	"slug"	"character varying"	"NO"		"UQ"		
"shipping_zones"	"description"	"text"	"YES"				
"shipping_zones"	"deliveryTime"	"character varying"	"YES"				
"shipping_zones"	"isActive"	"boolean"	"YES"	"true"			
"shipping_zones"	"createdAt"	"timestamp without time zone"	"YES"	"CURRENT_TIMESTAMP"			
"tipos_documento"	"id"	"integer"	"NO"	"nextval('tipos_documento_id_seq'::regclass)"	"PK"		
"tipos_documento"	"codigo"	"character varying"	"NO"		"UQ"		
"tipos_documento"	"nombre"	"character varying"	"NO"				
"tipos_documento"	"mascara"	"character varying"	"YES"				
"tipos_documento"	"longitud_min"	"integer"	"YES"	"7"			
"tipos_documento"	"longitud_max"	"integer"	"YES"	"12"			
"tipos_documento"	"requiere_digito_verificador"	"boolean"	"YES"	"false"			
"tipos_documento"	"activo"	"boolean"	"YES"	"true"			
"tipos_documento"	"orden"	"integer"	"YES"	"0"			
"tipos_documento"	"created_at"	"timestamp without time zone"	"YES"	"CURRENT_TIMESTAMP"			
"tipos_negocio"	"id"	"integer"	"NO"	"nextval('tipos_negocio_id_seq'::regclass)"	"PK"		
"tipos_negocio"	"codigo"	"character varying"	"NO"		"UQ"		
"tipos_negocio"	"nombre"	"character varying"	"NO"				
"tipos_negocio"	"icono"	"character varying"	"YES"				
"tipos_negocio"	"descripcion"	"text"	"YES"				
"tipos_negocio"	"campos_especiales"	"jsonb"	"YES"				
"tipos_negocio"	"activo"	"boolean"	"YES"	"true"			
"tipos_negocio"	"orden"	"integer"	"YES"	"0"			
"tipos_negocio"	"created_at"	"timestamp without time zone"	"YES"	"CURRENT_TIMESTAMP"			
"tipos_negocio"	"updated_at"	"timestamp without time zone"	"YES"	"CURRENT_TIMESTAMP"			
"tipos_persona"	"id"	"integer"	"NO"	"nextval('tipos_persona_id_seq'::regclass)"	"PK"		
"tipos_persona"	"codigo"	"character varying"	"NO"		"UQ"		
"tipos_persona"	"nombre"	"character varying"	"NO"				
"tipos_persona"	"descripcion"	"text"	"YES"				
"tipos_persona"	"requiere_razon_social"	"boolean"	"YES"	"false"			
"tipos_persona"	"requiere_nombre_completo"	"boolean"	"YES"	"true"			
"tipos_persona"	"campos_adicionales"	"jsonb"	"YES"				
"tipos_persona"	"activo"	"boolean"	"YES"	"true"			
"tipos_persona"	"orden"	"integer"	"YES"	"0"			
"tipos_persona"	"created_at"	"timestamp without time zone"	"YES"	"CURRENT_TIMESTAMP"			
"zonas_entrega"	"id"	"integer"	"NO"	"nextval('zonas_entrega_id_seq'::regclass)"	"PK"		
"zonas_entrega"	"estado_codigo"	"character varying"	"NO"		"UQ"		
"zonas_entrega"	"estado_nombre"	"character varying"	"NO"				
"zonas_entrega"	"zona_codigo"	"character varying"	"NO"		"UQ"		
"zonas_entrega"	"zona_nombre"	"character varying"	"NO"		"UQ"		
"zonas_entrega"	"activo"	"boolean"	"YES"	"true"			
"zonas_entrega"	"created_at"	"timestamp without time zone"	"YES"	"CURRENT_TIMESTAMP"			
"zonas_entrega"	"updated_at"	"timestamp without time zone"	"YES"	"CURRENT_TIMESTAMP"			
